runtime: go
api_version: go1

handlers:
  - url: /.*
    script: _go_app

env_variables:
  NAMESPACE: 'test'
  PROJECT_ID: 'jaju-running'
  STRAVA_CLIENT_ID: 'fake-id'
  STRAVA_CLIENT_SECRET: 'fake-secret'
  # DATASTORE_EMULATOR_HOST: 'localhost:8081'
